In [11]:
import numpy as np
import time
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
y = y/100

In [2]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [3]:
epoch=50000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = 2 #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [4]:
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [13]:
start_time=time.process_time()
for i in range(epoch):
#Forward Propogation
    neth1=np.dot(X,wh)+bh
    outh1 = sigmoid(neth1)
    neto1=np.dot(outh1,wout)+bout
    outo1 = sigmoid(neto1)

#Backpropagation
    deltak=(y-outo1)*(outo1)*(1-outo1)
    
    deltaj = deltak.dot(wout.T)*(outh1)*(1-outh1)
    
    wout += outh1.T.dot(deltak) *lr
    #bout += np.sum(deltak, axis=0,keepdims=True) *lr
    wh += X.T.dot(deltaj) *lr
    #bh += np.sum(deltaj, axis=0,keepdims=True) *lr

In [14]:
end_time=time.process_time()-start_time
print(end_time,"seconds")
print("Input: \n" + str(X)) 
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,outo1)

2.875 seconds
Input: 
[[2. 9.]
 [1. 5.]
 [3. 6.]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89898562]
 [0.87688401]
 [0.89206593]]
