In [1]:
print ("Hello World")

Hello World


In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
print(b)


[[1 2]
 [3 4]
 [5 6]]


In [4]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print (a)

[[1 2 3]
 [4 5 6]]


In [5]:
count=30
print(count)

30


In [6]:
name="Jaohn"
print(name)

Jaohn


In [7]:
print("hana")

hana


In [10]:
c=10.00000000001
print(c)

10.00000000001


In [12]:
s='Hello World'
print(s)

Hello World


In [13]:
print(s[0])

H


In [14]:
print(s[0:5])

Hello


In [15]:
print(s[:5])

Hello


In [16]:
print(s[0:])

Hello World


In [17]:
print(s[2:])

llo World


In [18]:
list1= [1,"Megha",2864999999999999999999, 2373.54453,c]

In [19]:
print(list1)

[1, 'Megha', 2864999999999999999999, 2373.54453, 10.00000000001]


In [20]:
list1= [1,"Megha",2864999999999999999999, 2373.54453,'c']

In [21]:
print(list1)

[1, 'Megha', 2864999999999999999999, 2373.54453, 'c']


In [22]:
print(list1[0])

1


In [23]:
print(list1[3])

2373.54453


In [24]:
print(list1[1:3])

['Megha', 2864999999999999999999]


In [25]:
print(list1[2:])

[2864999999999999999999, 2373.54453, 'c']


In [26]:
print(list1[:3])

[1, 'Megha', 2864999999999999999999]


In [27]:
print(list1[-1])

c


In [28]:
print(list1[-2])

2373.54453


In [29]:
list=[1,2,3]

In [30]:
print(list)

[1, 2, 3]


In [31]:
tuple=('abcd',343,3.4)
print(tuple)

('abcd', 343, 3.4)


In [32]:
print(tuple[0])
print(tuple[1:3])
print(tuple[1:])
print(tuple[:2])

abcd
(343, 3.4)
(343, 3.4)
('abcd', 343)


In [33]:
tuple[1]=1000

TypeError: 'tuple' object does not support item assignment

1000


In [36]:
print(tuple)

('abcd', 343, 3.4)


In [37]:
print(list)

[1, 2, 3]


In [38]:
list[1]=100

In [39]:
print(list)

[1, 100, 3]


In [42]:
dict={'name':'megha','dept':'cse','sem':6}


In [44]:
print(dict)

{'name': 'megha', 'dept': 'cse', 'sem': 6}


In [45]:
print(dict[0])

KeyError: 0

In [46]:
print(dict.keys())

dict_keys(['name', 'dept', 'sem'])


In [47]:
print(dict.values())

dict_values(['megha', 'cse', 6])


In [48]:
print(dict.keys(0))

TypeError: keys() takes no arguments (1 given)

In [49]:
print(dict.keys([0]))

TypeError: keys() takes no arguments (1 given)

In [52]:
print(dict['sem'])

6


In [53]:
print(dict['name'])

megha


In [60]:
import numpy as np
student= np.dtype([('name','S20'),('age','i1'),('marks','14')])
a=np.array([('abc',21,50),('fgdf',18,75)],dtype=student)
print(student)

TypeError: data type "" not understood